@echo off
echo Creando ambiente virtual...
py -3.10 -m venv venv
echo Activando ambiente virtual...
call venv\Scripts\activate
echo Instalando dependencias necesarias...
pip install kivy==2.2.1 kivymd==1.1.1 reportlab
echo Iniciando Taximetro Digital...
python taximetro.py
pause